create table if not exists public.personal_reminders (
    id bigint generated by default as identity primary key,
    title text not null,
    due_at timestamptz not null,
    source_update_id bigint unique,
    status text not null default 'pending'
        check (status in ('pending', 'sent', 'cancelled')),
    created_at timestamptz not null default now()
);

create index if not exists personal_reminders_pending_due_idx
    on public.personal_reminders (due_at)
    where status = 'pending';

create table if not exists public.app_state (
    key text primary key,
    value text not null
);

create table if not exists public.seen (
    key text primary key,
    kind text not null,
    ts double precision not null
);

alter table public.personal_reminders enable row level security;
alter table public.app_state enable row level security;
alter table public.seen enable row level security;
